[book]
authors = ["nix-enthusiast"]
language = "en"
src = "src"
title = "The Vega Programming Language"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/nix-enthusiast/vega"

#[output.pdf]
#pdf = true

[output.html.code.hidelines]
vega = ";;"